### PR TITLE
Minimal environment.yml plus .gitignore

### PR DESCRIPTION
**Pull request by johnyaku**
Hi Alexander,
Unfortunately the `conda env export` process that I suggested was not complete. It doesn't seem to capture pip installs and there may be other features of your development environment that were installed outside conda (such as perhaps compiler libraries or cuda libraries).
In any case, I now suspect that the approach illustrated in the environment.yml file in this pull request might be the way to go. I made this file manually and you'll notice that only a few versions are pinned or restrained. But there is also a two-stage installation with pip dependencies installed at the end, after all the conda installations.
This environment definition creates an environment that works on both my Mac and in Linux/Docker so long as I change the "device" flag in THEANO_FLAGS to "cpu".  Unfortunately it turns out that my GPU does not support cuda or opencl so I can't test the GPU options anyway. I hope to test this in the near future, and if I discover any missing dependencies required to get this to work I will let you know.
With this type of environment definition file (environment.yml) it is not easy to add additional packages after the environment has been created. The safest option is to delete the environment (`conda env remove -n countcorrect`) and then recreate it again (`conda env create -f environment.yml`). The `conda env update` subcommand doesn't seem to handle this kind of conda/pip mixed environment very well. But luckily the binaries will still be cached and so the recreation process is generally very fast.
I've also added a suggestion for .gitignore but because these files are already committed simply including .gitignore doesn't affect them. If you decide that cleaning up these files from the repo is a good idea then you'll have to something like this: [https://www.git-tower.com/learn/git/faq/ignore-tracked-files-in-git/](https://www.git-tower.com/learn/git/faq/ignore-tracked-files-in-git/) Note that this process does not remove the local files, only their presence in the repo.
I've also made a Docker image so that I can move code-plus-environment to other platforms but it is a bit bloated still. I'll share it once I have trimmed it down a bit.
Once I get it running I expect that I'll have a bunch more questions!

### CODE REVIEW

**Comment by johnyaku** [comment]
Btw, you can see what the repo would look like with the distribution files etc removed by looking at my fork of your repo. Happy to make another pull request for those changes if you like :)

**Comment by AlexanderAivazidis** [comment]
Ok thanks for that! If it takes too long with a cpu you can just decrease the iterations by specifying "total_iterations = 1000" for example, even 100 iterations gives good results. I will add something about that to the notebooks soon...

**Comment by johnyaku** [comment]
Thanks, that's helpful, especially during testing.

**Comment by johnyaku** [comment]
Btw, I found a problem with the environment.yml file that I proposed in the PR.

**Comment by johnyaku** [comment]
Sorry. Keeping hitting <return> too early! In environment.yml, the clangxx_osx-64 dependency is for Mac (osx). I swapped clangxx_osx-64 and libcxx for the more generic "cxx-compiler" and tested successfully on osx and Linux (CentOS 7.8). Also, under Linux theano complained about blas, so I added blas too. Still haven't tested with a GPU yet.

**Pull request merged**
