### PR TITLE
Pipeline script

### PR DESCRIPTION
**Pull request by johnyaku**
Hi. This pull request is intended to illustrate how we have been trying to use CountCorrect functions in our pipelines. Feel free to merge if you think this is worthwhile but mainly I would like to run this by you.
There are some minor changes to `environment.yml` but the main additions are in a folder called `pipeline`. If you choose to merge feel free to reorganise as you see fit. 
`cc.py` uses the `click` passage to take arguments from the command line, namely `--genes`, `--negs`, `--nuclei` and `--n_iter`. These arguments are used to initialise and fit a model, and then return some plots and CSV files along with the corrected count matrix. I am sure that this can be improved/extended.
In order to test cc.py, activate the conda environment and then run `pip install --editable pipeline/`

The script appears to work correctly for the demo data provided. However, when I run it on a large Nanostring dataset with 686 AOIs I run out of memory while sampling the posterior, despite requesting 192 GB RAM. I will continue to experiment with extra memory but I would like to inquire about one detail.

Does the model fit the distribution of negative probes independently for each AOI? Or are the negative probe counts for all AOIs considered collectively when fitting in the model?
That is, can I split the data set into smaller groups of samples in order to use less compute resources?  Or will that invalidate the assumptions of the algorithm?

### CODE REVIEW

**Comment by AlexanderAivazidis** [comment]
Hi! Thanks for this. I see I never used such a big dataset, but if memory is a problem then you can change this argument: posterior_samples = 100 to posterior_samples = 30, this should reduce memory requirements by 70% and give the same results (maybe I should change this by default). Otherwise, for very big data inputs the dataset would need to be split up yes. The model learns reoccurring patterns in gene expression and negative probe counts, so more data will improve the result, however less data does not invalidate any assumptions.

**Comment by johnyaku** [comment]
Thanks for the tips. The script now runs without running out of memory, even on the full data set.
The script returns a corrected count matrix, as well as several figures (for example, mean counts across ROIs versus mean estimated background counts, shaded by fraction removed). This all looks plausible, but I am bit bothered by the following:
- After fitting the model, `Average Loss` is reported as "nan".
- The plots generated by `model.plot_history()` are completely blank (regardless of start/end ranges)
I tried shifting the input count matrices by one to avoid log(0) and divide-by-zero errors, but the same issue still occurs.

Is this a problem? Is "average loss" the best overall measure of fit? Or is there a more appropriate measure?

Thanks again for your help!

**Comment by AlexanderAivazidis** [comment]
Hi, I have seen this happen with pymc3 models when some counts for some genes are very high. It is not really possible in single-cell RNAseq or Visium data, but in Nanostring some big ROIs can have a lot of UMI counts. This then causes some underflow problems in the pymc3 implementation of the Negative Binomial distribution for some genes or ROIs. But from what we have seen in different models (both CountCorrect and the cell2location algorithm) the optimization still converges to something sensible, even if the total loss is nan or inf. So it is not ideal, but probably still acceptable and nothing we can do in the short term.

**Comment by johnyaku** [comment]
Thanks Alexander!

**Pull request closed without merging**
